# Manual upload via twine:
# 1) Build project
# $ python setup.py sdist bdist_wheel
# 2) Upload via Twine with API token (user: __token__ password: <your API token>)
# $ python -m twine upload dist/*

name: Publish distributions ğŸ“¦ to PyPI

on:
  workflow_dispatch:
    branches:
      - master
      - main

jobs:
  build-n-publish:
    name: Build and publish ğŸ distributions ğŸ“¦ to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/lm-datasets
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-python@v4
      #with:
      #  python-version: 3.8
    - name: Build distribution
      run: |
        echo "$PWD"
        python setup.py sdist bdist_wheel
    - name: Publish distribution
      #if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
